; Recommended PHP settings for Moodle
; https://docs.moodle.org/500/en/PHP

memory_limit = 256M
max_execution_time = 300
max_input_time = 600
max_input_vars = 5000
post_max_size = 100M
upload_max_filesize = 100M
session.gc_maxlifetime = 7200
